---
- name: Update Root account's Route53 record
  hosts: localhost
  tasks:
  - name: update sandbox.qrious.co.nz record
    route53:
      command: create
      zone: qrious.co.nz
      record: sandbox.qrious.co.nz
      type: NS
      ttl: 300
      value: "{{ sandbox_ns_servers }}"
      wait: no
      profile: "{{ aws_profile }}"
      overwrite: true

- name: Create jenkins master group with it's public ip
  hosts: localhost
  tasks:
    - name: Add instance to master group
      add_host:
        hostname: jenkins
        ansible_ssh_host: "{{ jenkins_public_ip }}"
        ansible_ssh_user: admin
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
        groups:
          - jenkins

- name: Update jenkins VM
  hosts: jenkins
  gather_facts: true
  become: yes
  tasks:
    - name: install docker
      debug:
        var: hostname
    - name: install packages
      shell: |
        echo "update apt packages..."
        apt-get update
        echo "install dependencies packages..."
        apt install -y apt-transport-https ca-certificates curl software-properties-common gnupg2
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
        apt-get update
        apt install -y docker-ce
        systemctl enable docker
        systemctl start docker
        usermod -aG docker admin
      args:
        executable: /bin/bash
