---
- name: Update Route53 zone in root account with new VM's public ip
  hosts: localhost
  tasks:
    - name: assuming role required
      sts_assume_role:
        role_arn: "arn:aws:iam::630622130945:role/jenkins-assume-role-from-sandbox"
        role_session_name: assumed_role
        region: "ap-southeast-2"
      register: assumed_role

    - name: Create or Update a route53 record
      route53:
        state: present
        overwrite: true
        zone: qrious.co.nz
        record: jenkins.qrious.co.nz
        type: A
        ttl: 300
        value:
          - "{{ jenkins_public_ip }}"

        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
