
- name: Create jenkins master group with it's public ip
  hosts: localhost
  tasks:
    - name: Add instance to master group
      add_host:
        hostname: jenkins-master
        ansible_ssh_host: "{{ jenkins_public_ip }}"
        ansible_ssh_user: admin
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
        groups:
          - jenkins

- name: Run jenkins server inside docker
  hosts: jenkins
  gather_facts: true
  vars:
    ec2_private_key_content: "{{lookup('file', slave_private_key_file_path)}}"

  tasks:
    - name: create data directory for mount
      become: true
      file:
        path: /var/jenkins_home
        state: directory
        mode: '0777'

    - name: install docker-py
      pip:
        name: docker-py >= 1.7.0

    - name: delete existing jenkins instance
      docker_container:
        name: jenkins
        state: absent
      when: reset_docker == true

    - name: delete all files under /var/jenkins_home
      shell:
        rm -rf /var/jenkins_home/*
      when: reset_docker == true

    - name: run docker with jenkins/jenkins:lts image
      docker_container:
        name: jenkins
        pull: yes
        privileged: yes
        image: jenkins/jenkins:lts
#        image: jenkins/jenkins:2.176.4
        state: started
        restart_policy: always
        ports: 
          - "50000:50000"
          - "127.0.0.1:8080:8080"
        volumes:
          - /var/jenkins_home:/var/jenkins_home
        env:
          JENKINS_DNS_NAME: "{{jenkins_dns_name}}"

    - name: Waits for port 8080
      wait_for:
        host: 127.0.0.1
        port: 8080

    - name: Wait until the file /tmp/foo is present before continuing
      wait_for:
        path: /var/jenkins_home/secrets/initialAdminPassword

    - name: prepare password file
      shell:
        echo "admin:$(cat /var/jenkins_home/secrets/initialAdminPassword)" > /var/jenkins_home/admin.password

    - name: test web server - 1
      command:
        docker exec -it jenkins java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080 -auth @/var/jenkins_home/admin.password who-am-i

      retries: 10
      delay: 5
      register: result
      until: result.rc == 0

    - name: download ec2 plugin 1.45
      get_url:
        url: https://updates.jenkins-ci.org/download/plugins/ec2/1.45/ec2.hpi
        dest: /var/jenkins_home/ec2.hpi
      
    - name: install plugins
      shell: |
        docker exec -it jenkins java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080 -auth @/var/jenkins_home/admin.password  {{ item }}
      loop:
        - install-plugin ec2
        - install-plugin workflow-aggregator
        - install-plugin blueocean
        - install-plugin bitbucket
        - install-plugin configuration-as-code
        - install-plugin configuration-as-code-secret-ssm
        - install-plugin terraform
        - install-plugin ansicolor
        - install-plugin pipeline-utility-steps

    - name: download ec2 plugin 1.45
      shell: |
        rm -f /var/jenkins_home/plugins/ec2.jpi
        cp /var/jenkins_home/ec2.hpi /var/jenkins_home/plugins/ec2.jpi 

    - name: Restart Jenkins
      shell: |
        docker exec -it jenkins java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080 -auth @/var/jenkins_home/admin.password restart

    - name: test web server 2
      command:
        docker exec -it jenkins java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080 -auth @/var/jenkins_home/admin.password who-am-i

      retries: 10
      delay: 5
      register: result
      until: result.rc == 0

    - name: copy over the jenkins credential config file
      template:
        src: templates/jenkins.caas.cred.j2
        dest: //var/jenkins_home/jenkins.yaml

    - name: config cred with the caas file
      shell: |
        docker exec -it jenkins java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080 -auth @/var/jenkins_home/admin.password reload-jcasc-configuration

    - name: copy over the jenkins ec2 config file
      template:
        src: templates/jenkins.caas.ec2.j2
        dest: //var/jenkins_home/jenkins.yaml

    - name: config cred with the caas file for ec2
      shell: |
        docker exec -it jenkins java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080 -auth @/var/jenkins_home/admin.password reload-jcasc-configuration
