- name: Create jenkins master group with it's public ip
  hosts: localhost
  tasks:
    - name: Add instance to master group
      add_host:
        hostname: jenkins-master
        ansible_ssh_host: "{{ jenkins_public_ip }}"
        ansible_ssh_user: admin
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
        groups:
          - jenkins

- name: Install and configure certbot
  hosts: jenkins
  hosts: jenkins
  become: yes
  tasks:
    - name: Update repositories cache and install "pip" package
      apt:
        name: {{ item }}
	update_cache: yes
      loops:
        - python-pip
        - certbot

    - name: Run certbot command to acquire a certificate
      command: 
        certbot certonly --standalone -m sre.qrious@qrious.co.nz --agree-tos -n -d {{ jenkins_dns_name }}

  roles:
    - nginx-reverse-proxy

